version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped