version: '3.8'

services:
  # FastAPI 애플리케이션
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-python
    ports:
      - "8000:8000"
    volumes:
      # ./main.py 파일을 컨테이너 내부의 /app/main.py 경로에 마운트합니다.
      # 로컬에서 수정 시 컨테이너에 즉시 반영됩니다.
      - ./main.py:/app/main.py
      # 기존에 주석 처리된 모델 파일 마운트도 필요한 경우 주석을 해제합니다.
      # - ./model.pkl:/app/model.pkl:ro  # 모델 파일 마운트 (읽기 전용)
  
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/model.pkl
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092  # Docker 네트워크 내부 주소
      - REDIS_HOST=redis-server  # Docker 네트워크 내부 주소
      - REDIS_PORT=6379
      - REDIS_DB=0
    restart: unless-stopped
    networks:
      - app-network

  # Nginx (선택사항 - 프록시 서버) - 임시 비활성화
  # nginx:
  #   image: nginx:alpine
  #   container_name: income-prediction-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api
  #   restart: unless-stopped
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
    external: true
    name: 03_kafka_app-network
  